AWSTemplateFormatVersion: '2010-09-09'
Description: Template for Lambda Sample.
Parameters:
  EnvName:
    Type: String
    Description: Name of an environment. 'dev', 'staging', 'prod' and any name.
    AllowedPattern: ^.*[^0-9]$
    ConstraintDescription: Must end with non-numeric character.
    Default: "dev" #Environment variable
  lambdaImageUrl:
    Type: String
    Description: Skytrax lamb-data-query-resolver  #Default value is passed from buildspec.yml file
    
Resources:
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName:
        Fn::Sub: skytrax-lamb-data-query-resolver
      Description: LambdaFunction 
      Code:
          ImageUri: !Ref lambdaImageUrl #URI value is passed from buildspec.yml file
      MemorySize: 512
      EphemeralStorage: 
        Size: 512
      PackageType: "Image"
      Timeout: 15
      Role: "arn:aws:iam::832609808081:role/skytrax-lambrole-event-mgr" # keep the same role 'skytrax-lambrole-event-mgr' that has all permissions
      Environment:
        Variables:
          MICRONAUT_ENVIRONMENTS: !Ref EnvName